name: Salvar Pedidos
on:
  repository_dispatch:
    types: [novo_pedido]

jobs:
  salvar_pedido:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Salvar pedido
        run: |
          # Criar diretório se não existir
          mkdir -p docs/data
          
          # Ler orders.json atual ou criar array vazio
          if [ -f docs/data/orders.json ]; then
            ORDERS=$(cat docs/data/orders.json)
          else
            ORDERS="[]"
          fi
          
          # Adicionar novo pedido
          echo "$ORDERS" | jq '. += [${{ toJson(github.event.client_payload.pedido) }}]' > docs/data/orders.json
          
          # Commit e push
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add docs/data/orders.json
          git commit -m "Novo pedido: ${{ github.event.client_payload.pedido.number }}"
          git push
